adam: false
batch_size: 50
credit_algo: bp
learning_rule: bp
loss_multiplier: 1000
lr: 0.001
bio_decorr: False
net_structure:
- 784
- 500
- 500
- 500
- 500
- 500
- 500
- 10
outpath: ./results/MNIST/bp_decorr_boosted/
performances:
  test:
    acc: []
    loss: []
  train:
    acc: []
    loss: []
seed: 42
update_R: true
update_W: true
