adam: true
batch_size: 50
beta_1: 0.9
beta_2: 0.999
credit_algo: bp
epsilon: 1.0e-08
learning_rule: bp
loss_multiplier: 1
lr: 0.0001
net_structure:
- 3072
- 1000
- 1000
- 1000
- 1000
- 10
outpath: ./results/PerformanceTesting_C/bp_adam_0001/
performances:
  test:
    acc: []
    loss: []
  train:
    acc: []
    loss: []
seed: 42
update_R: false
update_W: true
